version: '3'
services:
  web:                             ## tag of the project  
    build: 
      context: .                   ## all the files in the folder
      dockerfile: Dockerfile.dev
    ports:
       - "3000:3000"
    volumes: 
      - /usr/app/node_modules           ## current folder outside the container
      - .:/usr/app                      ## folder in docker

                                     
  test:                             ## adding second service
    build: 
      context: .                   
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules           
      - .:/app                      
    command: ["npm", "run", "test"]
    


     ## docker-compose up 
     ## docker exec -it CONTAINER_ID sh  (allowing us to execute commands in the container)